export const voluntaryOrganizationsData = [
  {
    id: 1,
    name: "Banking for All",
    location: "New York, NY, USA",
    causes: "Banking",
    size: "Large",
    rating: 4.8,
  },
  {
    id: 2,
    name: "Books for Children",
    location: "Austin, TX, USA",
    causes: "Books",
    size: "Medium",
    rating: 4.5,
  },
  {
    id: 3,
    name: "Clothes Donation Drive",
    location: "Mumbai, Maharashtra, India",
    causes: "Clothes",
    size: "Small",
    rating: 4.3,
  },
  {
    id: 4,
    name: "College Admissions Support",
    location: "Chicago, IL, USA",
    causes: "College Admissions",
    size: "Medium",
    rating: 4.7,
  },
  {
    id: 5,
    name: "Cooking for Homeless",
    location: "Los Angeles, CA, USA",
    causes: "Cooking",
    size: "Large",
    rating: 4.9,
  },
  {
    id: 6,
    name: "Education for All",
    location: "London, England, UK",
    causes: "Education",
    size: "Large",
    rating: 4.6,
  },
  {
    id: 7,
    name: "Employment Services",
    location: "Berlin, Germany",
    causes: "Employment",
    size: "Medium",
    rating: 4.4,
  },
  {
    id: 8,
    name: "Finance Literacy Group",
    location: "Toronto, Ontario, Canada",
    causes: "Finance",
    size: "Small",
    rating: 4.3,
  },
  {
    id: 9,
    name: "Food For Everyone",
    location: "Nairobi, Kenya",
    causes: "Food",
    size: "Large",
    rating: 4.5,
  },
  {
    id: 10,
    name: "Gardening for Good",
    location: "Sydney, NSW, Australia",
    causes: "Gardening",
    size: "Small",
    rating: 4.6,
  },
  {
    id: 11,
    name: "Housing Help Foundation",
    location: "San Francisco, CA, USA",
    causes: "Housing",
    size: "Medium",
    rating: 4.7,
  },
  {
    id: 12,
    name: "Homeless Aid Group",
    location: "Cape Town, South Africa",
    causes: "Homelessness",
    size: "Small",
    rating: 4.3,
  },
  {
    id: 13,
    name: "Sports for All",
    location: "Paris, France",
    causes: "Sports",
    size: "Medium",
    rating: 4.7,
  },
  {
    id: 14,
    name: "Jobs for Youth",
    location: "Tokyo, Japan",
    causes: "Jobs",
    size: "Large",
    rating: 4.6,
  },
  {
    id: 15,
    name: "Medical Aid Group",
    location: "Brasília, Brazil",
    causes: "Medical",
    size: "Large",
    rating: 4.8,
  },
];
