version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Running tests...
      - npm run test
      - echo Building the app...
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: dist
