coverage:
  range: "80...90"
  status:
    project:
      default: # default is the status check's name, not default settings
        target: auto
        threshold: 1
    patch:
      default: # default is the status check's name, not default settings
        target: 90%
        threshold: 0
