// Mock data with new categories and request ID format
export const requestsData = {
  myRequests: {
    data: [
      {
        id: "REQ-00-000-000-0001",
        type: "IN_PERSON",
        subject: "Need headphone repair",
        description:
          "My wireless headphones stopped working and I need help finding someone who can repair them or advise on replacement options.",
        creationDate: "2024-11-15T10:30:00Z",
        updatedDate: "2024-11-20T14:45:00Z",
        status: "RESOLVED",
        category: "BUY_THINGS",
        priority: "HIGH",
        calamity: "None",
      },
      {
        id: "REQ-00-000-000-0002",
        type: "REMOTE",
        subject: "Medicine pickup from pharmacy",
        description:
          "I need assistance picking up my prescription medication from the local pharmacy as I am unable to travel there myself.",
        creationDate: "2024-12-01T08:15:00Z",
        updatedDate: "2024-12-05T16:30:00Z",
        status: "MATCHING_VOLUNTEER",
        category: "MEDICINE_DELIVERY",
        priority: "CRITICAL",
        calamity: "None",
      },
      {
        id: "REQ-00-000-000-0003",
        type: "IN_PERSON",
        subject: "Laptop screen replacement",
        description:
          "My laptop screen is cracked and needs replacement. Looking for guidance on where to get it repaired or help with the repair process.",
        creationDate: "2024-12-03T09:00:00Z",
        updatedDate: null,
        status: "CREATED",
        category: "BUY_THINGS",
        priority: "HIGH",
        calamity: "None",
      },
      {
        id: "REQ-00-000-000-0004",
        type: "IN_PERSON",
        subject: "Weekly groceries delivery",
        description:
          "I need help with weekly grocery shopping and delivery. Prefer someone who can help select fresh produce and deliver to my home.",
        creationDate: "2024-12-05T11:20:00Z",
        updatedDate: "2024-12-08T10:00:00Z",
        status: "MANAGED",
        category: "GROCERY_SHOPPING_AND_DELIVERY",
        priority: "MEDIUM",
        calamity: "None",
      },
      {
        id: "REQ-00-000-000-0005",
        type: "REMOTE",
        subject: "Pick up dry cleaning",
        description:
          "Need someone to pick up my dry cleaning from the shop and deliver it to my address this week.",
        creationDate: "2024-12-06T07:45:00Z",
        updatedDate: "2024-12-10T08:00:00Z",
        status: "CANCELLED",
        category: "ERRANDS_EVENTS_TRANSPORTATION",
        priority: "LOW",
        calamity: "None",
      },
      {
        id: "REQ-00-000-000-0006",
        type: "IN_PERSON",
        subject: "Return books to library",
        description:
          "I have several library books that are due and need help returning them to the local library branch.",
        creationDate: "2024-12-07T13:10:00Z",
        updatedDate: null,
        status: "CREATED",
        category: "EDUCATION_RESOURCE_SHARING",
        priority: "MEDIUM",
        calamity: "None",
      },
      {
        id: "REQ-00-000-000-0007",
        type: "REMOTE",
        subject: "House deep cleaning service",
        description:
          "Looking for help arranging a professional deep cleaning service for my home, including guidance on reliable service providers.",
        creationDate: "2024-11-28T15:00:00Z",
        updatedDate: "2024-12-02T18:30:00Z",
        status: "RESOLVED",
        category: "REPAIR_MAINTENANCE_SUPPORT",
        priority: "HIGH",
        calamity: "None",
      },
      {
        id: "REQ-00-000-000-0008",
        type: "IN_PERSON",
        subject: "Car wash and detailing",
        description:
          "Need assistance finding and scheduling a car wash and detailing service in my area.",
        creationDate: "2024-12-08T10:30:00Z",
        updatedDate: null,
        status: "CREATED",
        category: "ERRANDS_EVENTS_TRANSPORTATION",
        priority: "LOW",
        calamity: "None",
      },
      {
        id: "REQ-00-000-000-0009",
        type: "IN_PERSON",
        subject: "Daily dog walking service",
        description:
          "My dog needs daily walks while I'm recovering from surgery. Looking for a reliable person to walk my dog for the next few weeks.",
        creationDate: "2024-12-09T06:00:00Z",
        updatedDate: "2024-12-10T08:00:00Z",
        status: "MANAGED",
        category: "SOCIAL_CONNECTION",
        priority: "MEDIUM",
        calamity: "None",
      },
      {
        id: "REQ-00-000-000-0010",
        type: "REMOTE",
        subject: "Grocery shopping assistance",
        description:
          "Need help with grocery shopping - someone to accompany me or shop for me based on a list I'll provide.",
        creationDate: "2024-12-10T12:00:00Z",
        updatedDate: null,
        status: "MATCHING_VOLUNTEER",
        category: "GROCERY_SHOPPING_AND_DELIVERY",
        priority: "MEDIUM",
        calamity: "None",
      },
    ],
  },
  othersRequests: {
    data: [
      {
        id: "REQ-00-000-000-0011",
        type: "IN_PERSON",
        subject: "Donate old clothes to charity",
        description:
          "I have bags of gently used clothes to donate and need help transporting them to a local charity or donation center.",
        creationDate: "2024-12-02T14:20:00Z",
        updatedDate: "2024-12-04T16:00:00Z",
        status: "RESOLVED",
        category: "DONATE_CLOTHES",
        priority: "LOW",
        calamity: "None",
      },
      {
        id: "REQ-00-000-000-0012",
        type: "REMOTE",
        subject: "Help organize community event",
        description:
          "Planning a community gathering and need help with organization, including venue booking and coordinating with participants.",
        creationDate: "2024-11-25T09:30:00Z",
        updatedDate: "2024-11-30T11:00:00Z",
        status: "MANAGED",
        category: "SOCIAL_CONNECTION",
        priority: "HIGH",
        calamity: "None",
      },
      {
        id: "REQ-00-000-000-0013",
        type: "IN_PERSON",
        subject: "Create marketing flyers",
        description:
          "Need assistance designing and printing marketing flyers for a local community initiative.",
        creationDate: "2024-12-01T10:00:00Z",
        updatedDate: null,
        status: "CREATED",
        category: "GENERAL_CATEGORY",
        priority: "MEDIUM",
        calamity: "None",
      },
      {
        id: "REQ-00-000-000-0014",
        type: "REMOTE",
        subject: "File tax documents",
        description:
          "I need help organizing and filing my tax documents, including guidance on what needs to be submitted.",
        creationDate: "2024-12-03T08:00:00Z",
        updatedDate: "2024-12-06T12:00:00Z",
        status: "MATCHING_VOLUNTEER",
        category: "SCHEDULING_APPOINTMENTS_OR_TASKS",
        priority: "HIGH",
        calamity: "None",
      },
      {
        id: "REQ-00-000-000-0015",
        type: "IN_PERSON",
        subject: "Research local childcare options",
        description:
          "Urgently need help researching and evaluating local childcare facilities for my toddler, including visiting centers and comparing options.",
        creationDate: "2024-12-04T11:45:00Z",
        updatedDate: null,
        status: "CREATED",
        category: "SOCIAL_CONNECTION",
        priority: "CRITICAL",
        calamity: "None",
      },
    ],
  },
  managedRequests: {
    data: [
      {
        id: "REQ-00-000-000-0016",
        type: "REMOTE",
        subject: "Market analysis report needed",
        description:
          "Looking for assistance conducting market research and preparing an analysis report for a small business project.",
        creationDate: "2024-11-20T13:00:00Z",
        updatedDate: "2024-11-28T15:30:00Z",
        status: "RESOLVED",
        category: "CAREER_GUIDANCE",
        priority: "HIGH",
        calamity: "None",
      },
      {
        id: "REQ-00-000-000-0017",
        type: "IN_PERSON",
        subject: "Emergency food supplies delivery",
        description:
          "Emergency situation - need immediate delivery of essential food supplies due to unexpected circumstances preventing me from leaving home.",
        creationDate: "2024-12-09T07:00:00Z",
        updatedDate: "2024-12-09T09:00:00Z",
        status: "MANAGED",
        category: "FOOD_ASSISTANCE",
        priority: "CRITICAL",
        calamity: "Yes",
      },
      {
        id: "REQ-00-000-000-0018",
        type: "IN_PERSON",
        subject: "Medical equipment transport",
        description:
          "Need urgent help transporting medical equipment (wheelchair and oxygen concentrator) to my new temporary residence.",
        creationDate: "2024-12-08T06:30:00Z",
        updatedDate: null,
        status: "MATCHING_VOLUNTEER",
        category: "MEDICAL_DEVICES_SETUP",
        priority: "HIGH",
        calamity: "Yes",
      },
      {
        id: "REQ-00-000-000-0019",
        type: "REMOTE",
        subject: "Tutoring for math homework",
        description:
          "My child needs help with algebra homework. Looking for someone who can provide remote tutoring sessions twice a week.",
        creationDate: "2024-12-05T16:00:00Z",
        updatedDate: "2024-12-07T17:30:00Z",
        status: "MANAGED",
        category: "TUTORING",
        priority: "MEDIUM",
        calamity: "None",
      },
      {
        id: "REQ-00-000-000-0020",
        type: "IN_PERSON",
        subject: "Package delivery to post office",
        description:
          "Have a package that needs to be dropped off at the post office for international shipping.",
        creationDate: "2024-12-10T09:15:00Z",
        updatedDate: null,
        status: "CREATED",
        category: "ERRANDS_EVENTS_TRANSPORTATION",
        priority: "LOW",
        calamity: "None",
      },
    ],
  },
};
