export const requestsData = {
  myRequests: {
    data: [
      {
        id: 1,
        type: "Personal",
        subject: "Need headphone",
        creationDate: "2024-06-01",
        closedDate: null,
        status: "Open",
        category: "Electronics",
        priority: "High",
        calamity: "None",
      },
      {
        id: 2,
        type: "Personal",
        subject: "Medicine pickup",
        creationDate: "2024-06-10",
        closedDate: null,
        status: "Open",
        category: "Health",
        priority: "Medium",
        calamity: "None",
      },
      {
        id: 3,
        type: "Personal",
        subject: "Laptop repair",
        creationDate: "2024-06-11",
        closedDate: null,
        status: "Open",
        category: "Electronics",
        priority: "High",
        calamity: "None",
      },
      {
        id: 4,
        type: "Personal",
        subject: "Groceries delivery",
        creationDate: "2024-06-12",
        closedDate: null,
        status: "Open",
        category: "Essentials",
        priority: "Medium",
        calamity: "None",
      },
      {
        id: 5,
        type: "Personal",
        subject: "Pick up dry cleaning",
        creationDate: "2024-06-13",
        closedDate: null,
        status: "Open",
        category: "Logistics",
        priority: "Low",
        calamity: "None",
      },
      {
        id: 6,
        type: "Personal",
        subject: "Book return to library",
        creationDate: "2024-06-14",
        closedDate: null,
        status: "Open",
        category: "Education",
        priority: "Medium",
        calamity: "None",
      },
      {
        id: 7,
        type: "Personal",
        subject: "House cleaning",
        creationDate: "2024-06-15",
        closedDate: null,
        status: "Open",
        category: "Maintenance",
        priority: "High",
        calamity: "None",
      },
      {
        id: 8,
        type: "Personal",
        subject: "Car wash",
        creationDate: "2024-06-16",
        closedDate: null,
        status: "Open",
        category: "Maintenance",
        priority: "Low",
        calamity: "None",
      },
      {
        id: 9,
        type: "Personal",
        subject: "Dog walking",
        creationDate: "2024-06-17",
        closedDate: null,
        status: "Open",
        category: "Pets",
        priority: "Medium",
        calamity: "None",
      },
      {
        id: 10,
        type: "Personal",
        subject: "Buy gift",
        creationDate: "2024-06-18",
        closedDate: null,
        status: "Open",
        category: "Shopping",
        priority: "High",
        calamity: "None",
      },
      {
        id: 11,
        type: "Personal",
        subject: "Phone repair",
        creationDate: "2024-06-19",
        closedDate: null,
        status: "Open",
        category: "Electronics",
        priority: "High",
        calamity: "None",
      },
      {
        id: 12,
        type: "Personal",
        subject: "Grocery shopping",
        creationDate: "2024-06-20",
        closedDate: null,
        status: "Open",
        category: "Essentials",
        priority: "Medium",
        calamity: "None",
      },
      {
        id: 13,
        type: "Personal",
        subject: "Pet vaccination",
        creationDate: "2024-06-21",
        closedDate: null,
        status: "Open",
        category: "Pets",
        priority: "High",
        calamity: "None",
      },
      {
        id: 14,
        type: "Personal",
        subject: "Visit doctor",
        creationDate: "2024-06-22",
        closedDate: null,
        status: "Open",
        category: "Health",
        priority: "Medium",
        calamity: "None",
      },
      {
        id: 15,
        type: "Personal",
        subject: "Water delivery",
        creationDate: "2024-06-23",
        closedDate: null,
        status: "Open",
        category: "Essentials",
        priority: "Low",
        calamity: "None",
      },
      {
        id: 16,
        type: "Personal",
        subject: "Yoga session",
        creationDate: "2024-06-24",
        closedDate: null,
        status: "Open",
        category: "Health",
        priority: "Medium",
        calamity: "None",
      },
      {
        id: 17,
        type: "Personal",
        subject: "Laundry pickup",
        creationDate: "2024-06-25",
        closedDate: null,
        status: "Open",
        category: "Logistics",
        priority: "Low",
        calamity: "None",
      },
      {
        id: 18,
        type: "Personal",
        subject: "Car repair",
        creationDate: "2024-06-26",
        closedDate: null,
        status: "Open",
        category: "Maintenance",
        priority: "High",
        calamity: "None",
      },
      {
        id: 19,
        type: "Personal",
        subject: "Book shopping",
        creationDate: "2024-06-27",
        closedDate: null,
        status: "Open",
        category: "Shopping",
        priority: "Medium",
        calamity: "None",
      },
      {
        id: 20,
        type: "Personal",
        subject: "Home repair",
        creationDate: "2024-06-28",
        closedDate: null,
        status: "Open",
        category: "Maintenance",
        priority: "Low",
        calamity: "None",
      },
      {
        id: 21,
        type: "Personal",
        subject: "Pick up prescription",
        creationDate: "2024-06-29",
        closedDate: null,
        status: "Open",
        category: "Health",
        priority: "High",
        calamity: "None",
      },
      {
        id: 22,
        type: "Personal",
        subject: "Library book renewal",
        creationDate: "2024-06-30",
        closedDate: null,
        status: "Open",
        category: "Education",
        priority: "Low",
        calamity: "None",
      },
      {
        id: 23,
        type: "Personal",
        subject: "Gardening supplies",
        creationDate: "2024-07-01",
        closedDate: null,
        status: "Open",
        category: "Maintenance",
        priority: "Medium",
        calamity: "None",
      },
      {
        id: 24,
        type: "Personal",
        subject: "Buy groceries",
        creationDate: "2024-07-02",
        closedDate: null,
        status: "Open",
        category: "Essentials",
        priority: "Medium",
        calamity: "None",
      },
      {
        id: 25,
        type: "Personal",
        subject: "Pick up gift",
        creationDate: "2024-07-03",
        closedDate: null,
        status: "Open",
        category: "Shopping",
        priority: "High",
        calamity: "None",
      },
      {
        id: 26,
        type: "Personal",
        subject: "Maid service",
        creationDate: "2024-07-04",
        closedDate: null,
        status: "Open",
        category: "Maintenance",
        priority: "Low",
        calamity: "None",
      },
      {
        id: 27,
        type: "Personal",
        subject: "Fitness class",
        creationDate: "2024-07-05",
        closedDate: null,
        status: "Open",
        category: "Health",
        priority: "Medium",
        calamity: "None",
      },
      {
        id: 28,
        type: "Personal",
        subject: "Food delivery",
        creationDate: "2024-07-06",
        closedDate: null,
        status: "Open",
        category: "Essentials",
        priority: "Low",
        calamity: "None",
      },
      {
        id: 29,
        type: "Personal",
        subject: "Vacation planning",
        creationDate: "2024-07-07",
        closedDate: null,
        status: "Open",
        category: "Personal",
        priority: "Medium",
        calamity: "None",
      },
      {
        id: 30,
        type: "Personal",
        subject: "Buy laptop accessories",
        creationDate: "2024-07-08",
        closedDate: null,
        status: "Open",
        category: "Electronics",
        priority: "High",
        calamity: "None",
      },
      {
        id: 31,
        type: "Personal",
        subject: "Donate clothes",
        creationDate: "2024-07-09",
        closedDate: null,
        status: "Open",
        category: "Charity",
        priority: "Low",
        calamity: "None",
      },
      {
        id: 32,
        type: "Personal",
        subject: "Meeting with friend",
        creationDate: "2024-07-10",
        closedDate: null,
        status: "Open",
        category: "Social",
        priority: "Medium",
        calamity: "None",
      },
      {
        id: 33,
        type: "Personal",
        subject: "Schedule dentist appointment",
        creationDate: "2024-07-11",
        closedDate: null,
        status: "Open",
        category: "Health",
        priority: "High",
        calamity: "None",
      },
      {
        id: 34,
        type: "Personal",
        subject: "Buy shoes",
        creationDate: "2024-07-12",
        closedDate: null,
        status: "Open",
        category: "Shopping",
        priority: "Medium",
        calamity: "None",
      },
      {
        id: 35,
        type: "Personal",
        subject: "Clean windows",
        creationDate: "2024-07-13",
        closedDate: null,
        status: "Open",
        category: "Maintenance",
        priority: "Low",
        calamity: "None",
      },
      {
        id: 36,
        type: "Personal",
        subject: "Buy kitchen appliances",
        creationDate: "2024-07-14",
        closedDate: null,
        status: "Open",
        category: "Electronics",
        priority: "High",
        calamity: "None",
      },
      {
        id: 37,
        type: "Personal",
        subject: "Install software",
        creationDate: "2024-07-15",
        closedDate: null,
        status: "Open",
        category: "Electronics",
        priority: "Medium",
        calamity: "None",
      },
      {
        id: 38,
        type: "Personal",
        subject: "Attend seminar",
        creationDate: "2024-07-16",
        closedDate: null,
        status: "Open",
        category: "Education",
        priority: "Low",
        calamity: "None",
      },
      {
        id: 39,
        type: "Personal",
        subject: "Check car insurance",
        creationDate: "2024-07-17",
        closedDate: null,
        status: "Open",
        category: "Maintenance",
        priority: "Medium",
        calamity: "None",
      },
      {
        id: 40,
        type: "Personal",
        subject: "Visit family",
        creationDate: "2024-07-18",
        closedDate: null,
        status: "Open",
        category: "Personal",
        priority: "Low",
        calamity: "None",
      },
      {
        id: 41,
        type: "Personal",
        subject: "Buy birthday gift",
        creationDate: "2024-07-19",
        closedDate: null,
        status: "Open",
        category: "Shopping",
        priority: "High",
        calamity: "None",
      },
      {
        id: 42,
        type: "Personal",
        subject: "Take car to service",
        creationDate: "2024-07-20",
        closedDate: null,
        status: "Open",
        category: "Maintenance",
        priority: "High",
        calamity: "None",
      },
      {
        id: 43,
        type: "Personal",
        subject: "Pick up groceries",
        creationDate: "2024-07-21",
        closedDate: null,
        status: "Open",
        category: "Essentials",
        priority: "Medium",
        calamity: "None",
      },
      {
        id: 44,
        type: "Personal",
        subject: "Buy phone accessories",
        creationDate: "2024-07-22",
        closedDate: null,
        status: "Open",
        category: "Electronics",
        priority: "Low",
        calamity: "None",
      },
      {
        id: 45,
        type: "Personal",
        subject: "Organize home",
        creationDate: "2024-07-23",
        closedDate: null,
        status: "Open",
        category: "Maintenance",
        priority: "Low",
        calamity: "None",
      },
    ],
  },
  othersRequests: {
    data: [
      {
        id: 1,
        type: "For Others",
        subject: "Help picking up the delivery",
        creationDate: "2024-06-03",
        closedDate: null,
        status: "Open",
        category: "Logistics",
        priority: "Low",
        calamity: "None",
      },
      {
        id: 2,
        type: "For Others",
        subject: "Collect donations",
        creationDate: "2024-06-12",
        closedDate: "2024-06-15",
        status: "Closed",
        category: "Charity",
        priority: "High",
        calamity: "None",
      },
      {
        id: 3,
        type: "For Others",
        subject: "Help move furniture",
        creationDate: "2024-06-13",
        closedDate: null,
        status: "Open",
        category: "Logistics",
        priority: "Medium",
        calamity: "None",
      },
      {
        id: 4,
        type: "For Others",
        subject: "Run errands",
        creationDate: "2024-06-14",
        closedDate: null,
        status: "Open",
        category: "Logistics",
        priority: "High",
        calamity: "None",
      },
      {
        id: 5,
        type: "For Others",
        subject: "Grocery shopping",
        creationDate: "2024-06-15",
        closedDate: null,
        status: "Open",
        category: "Essentials",
        priority: "High",
        calamity: "None",
      },
      {
        id: 6,
        type: "For Others",
        subject: "Help with gardening",
        creationDate: "2024-06-16",
        closedDate: null,
        status: "Open",
        category: "Maintenance",
        priority: "Low",
        calamity: "None",
      },
      {
        id: 7,
        type: "For Others",
        subject: "Cook meals",
        creationDate: "2024-06-17",
        closedDate: null,
        status: "Open",
        category: "Essentials",
        priority: "Medium",
        calamity: "None",
      },
      {
        id: 8,
        type: "For Others",
        subject: "Babysitting",
        creationDate: "2024-06-18",
        closedDate: null,
        status: "Open",
        category: "Childcare",
        priority: "High",
        calamity: "None",
      },
      {
        id: 9,
        type: "For Others",
        subject: "Pet sitting",
        creationDate: "2024-06-19",
        closedDate: null,
        status: "Open",
        category: "Pets",
        priority: "Medium",
        calamity: "None",
      },
      {
        id: 10,
        type: "For Others",
        subject: "House cleaning",
        creationDate: "2024-06-20",
        closedDate: null,
        status: "Open",
        category: "Maintenance",
        priority: "High",
        calamity: "None",
      },
    ],
  },
  managedRequests: {
    data: [
      {
        id: 1,
        type: "Managed",
        subject: "Grocery Delivery",
        creationDate: "2024-06-03",
        closedDate: null,
        status: "Open",
        category: "Essentials",
        priority: "Medium",
        calamity: "None",
      },
      {
        id: 2,
        type: "Managed",
        subject: "Manage donations",
        creationDate: "2024-06-12",
        closedDate: "2024-06-15",
        status: "Closed",
        category: "Charity",
        priority: "High",
        calamity: "None",
      },
      {
        id: 3,
        type: "Managed",
        subject: "Coordinate volunteers",
        creationDate: "2024-06-13",
        closedDate: null,
        status: "Open",
        category: "Logistics",
        priority: "High",
        calamity: "None",
      },
      {
        id: 4,
        type: "Managed",
        subject: "Set up event",
        creationDate: "2024-06-14",
        closedDate: null,
        status: "Open",
        category: "Events",
        priority: "Medium",
        calamity: "None",
      },
      {
        id: 5,
        type: "Managed",
        subject: "Distribute flyers",
        creationDate: "2024-06-15",
        closedDate: null,
        status: "Open",
        category: "Marketing",
        priority: "Low",
        calamity: "None",
      },
      {
        id: 6,
        type: "Managed",
        subject: "Prepare reports",
        creationDate: "2024-06-16",
        closedDate: null,
        status: "Open",
        category: "Administration",
        priority: "Medium",
        calamity: "None",
      },
      {
        id: 7,
        type: "Managed",
        subject: "Social media updates",
        creationDate: "2024-06-17",
        closedDate: null,
        status: "Open",
        category: "Marketing",
        priority: "High",
        calamity: "None",
      },
      {
        id: 8,
        type: "Managed",
        subject: "Arrange transport",
        creationDate: "2024-06-18",
        closedDate: null,
        status: "Open",
        category: "Logistics",
        priority: "Medium",
        calamity: "None",
      },
      {
        id: 9,
        type: "Managed",
        subject: "Organize storage",
        creationDate: "2024-06-19",
        closedDate: null,
        status: "Open",
        category: "Logistics",
        priority: "Low",
        calamity: "None",
      },
      {
        id: 10,
        type: "Managed",
        subject: "Conduct surveys",
        creationDate: "2024-06-20",
        closedDate: null,
        status: "Open",
        category: "Research",
        priority: "Medium",
        calamity: "None",
      },
    ],
  },
};
