name: Code Coverage

on:
  # Triggers the workflow on push or pull request events
  pull_request:
    branches: ["lorkenpeist/coverage"]

jobs:
  coverage:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull_request: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Jest coverage report
        uses: ArtiomTr/jest-coverage-report-action@v2.3.1
