name: Code Coverage

on:
  # Triggers the workflow on push or pull request events
  pull_request:
    branches: ["lorkenpeist/codecov"]
  push:
    #TODO: Remove this after base report is uploaded
    branches: ["lorkenpeist/codecov"]

jobs:
  coverage:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Run tests with coverage
        run: npm run test:coverage
        continue-on-error: true

      - uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
