name: e2epipeline

on:
  push:
    branches: ["test", "dev", "main","dockerTest"]
  pull_request:
    branches: ["test", "dev", "main"]
  workflow_dispatch:

jobs:
  nightwatch_tests:
    name: Ejecutar pruebas Nightwatch
    runs-on: ubuntu-latest
    container:
      image: moddebaixa/saayamimage:latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Run E2E (build already hecho, preview + wait + e2e)
        run: npx start-server-and-test preview http://localhost:4173 e2e