# This is a basic workflow to help you get started with Actions

name: CI/CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
    branches: ["test", "arjun-netlify-deploy-test"]
  pull_request:
    branches: ["test", "dev", "main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Node.js Setup
        uses: actions/setup-node@v4
        with:
          node-version: "21"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Testing
        run: npm test

      - name: Build application
        run: npm run build

      - name: Test the build
        run: |
          npm run dev &
          sleep 10
          curl --retry 3 --retry-delay 5 -f http://localhost:5173
          kill %1

      - name: Build
        run: npm run build
        
      - name: Zip the build
        run: zip -r build.zip build/
      	
      - name: Deploy to netlify
        run: curl -X POST -H "Content-Type:application/zip" -H "Authorization:Bearer nfp_uzHm5k7QSvQBQXoyMzZnYwenhwvgNF99ed6f" --data-binary "@build.zip" https://api.netlify.com/api/v1/sites/3252d3cb-6200-4dd6-8646-8641ca48e452/deploys
