name: Run webapp and Selenium tests

on:
  push:
    branches: ["test", "dockerTest"]
  pull_request:
    branches: ["test"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install and start React app
        working-directory: .
        run: |
          npm install
          npm run build
          nohup npm run preview &          # Levanta la app en background
          APP_PORT=4173                    # Ajusta al puerto que uses
          echo "Waiting for React app to be ready..."
          for i in {1..30}; do             # Máximo 30 intentos
            if curl -s http://localhost:$APP_PORT > /dev/null; then
              echo "App is up!"
              break
            fi
            echo "Waiting for app... ($i)"
            sleep 2
          done
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install system dependencies (Chrome, Firefox, Edge)
        run: |
          sudo apt-get update
          # Chrome
          sudo apt-get install -y google-chrome-stable
      - name: Setup Microsoft Edge
        uses: browser-actions/setup-edge@v1
        with:
          edge-version: stable

      - name: Install Firefox
        run: |
          sudo add-apt-repository -y ppa:mozillateam/ppa
          sudo apt-get update
          sudo apt-get install -y firefox

      # ChromeDriver
      - name: Install ChromeDriver
        uses: nanasess/setup-chromedriver@v2

      # GeckoDriver (para Firefox)
      - name: Install GeckoDriver (static version)
        run: |
          wget -q https://github.com/mozilla/geckodriver/releases/download/v0.35.0/geckodriver-v0.35.0-linux64.tar.gz
          tar -xvzf geckodriver-v0.35.0-linux64.tar.gz
          sudo mv geckodriver /usr/local/bin/
          geckodriver --version

      # EdgeDriver (para Edge)
      #      - name: Install EdgeDriver
      #        run: |
      #          EDGE_VERSION=$(microsoft-edge --version | awk '{print $3}')
      #          wget "https://msedgedriver.azureedge.net/${EDGE_VERSION}/edgedriver_linux64.zip"
      #          unzip edgedriver_linux64.zip
      #          sudo mv msedgedriver /usr/local/bin/
      #
      - name: Install Python dependencies
        working-directory: ./e2e-tests
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest selenium webdriver-manager

      - name: Run pytest in chrome
        working-directory: ./e2e-tests
        env:
          PYTHONUNBUFFERED: 1
        run: |
          pytest
        continue-on-error: true
      - name: Run pytest in firefox
        working-directory: ./e2e-tests
        env:
          PYTHONUNBUFFERED: 1
        run: |

          pytest --browser=firefox
        continue-on-error: true
      - name: Run pytest in edge
        working-directory: ./e2e-tests
        env:
          PYTHONUNBUFFERED: 1
        run: |

          pytest --browser=edge
