name: Run webapp and Selenium tests

on:
  push:
    branches: ["test","dockerTest"]
  pull_request:
    branches: ["test"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install and start React app
        working-directory: .
        run: |
          npm install
          npm run build
          nohup npm run preview &  # Evita que el preview bloquee el hilo
          sleep 10

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install system dependencies (Chrome)
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install ChromeDriver
        uses: nanasess/setup-chromedriver@v2

      - name: Install Python dependencies
        working-directory: ./e2e-tests
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest selenium webdriver-manager

      - name: Run pytest
        working-directory: ./e2e-tests
        env:
          PYTHONUNBUFFERED: 1
        run: |
          pytest
